# Generated by Django 6.1.1 on 2026-10-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyRequests',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('required_blood_type', models.CharField(max_length=3)),
                ('component_type', models.CharField(max_length=30)),
                ('units_required', models.IntegerField()),
                ('urgency', models.CharField(max_length=20)),
                ('radius_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'emergency_requests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('notification_type', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('delivery_channel', models.CharField(max_length=20)),
                ('delivery_status', models.CharField(max_length=20)),
                ('retry_count', models.IntegerField()),
                ('is_read', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notifications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RequestMatches',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('match_score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('notification_status', models.CharField(max_length=20)),
                ('response_status', models.CharField(max_length=20)),
                ('matched_at', models.DateTimeField()),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'request_matches',
                'managed': False,
            },
        ),
    ]
