# Generated by Django 6.1.1 on 2026-10-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('donation_type', models.CharField(max_length=30)),
                ('appointment_source', models.CharField(max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'appointments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('actual_component_type', models.CharField(max_length=30)),
                ('completed_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'donations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FacilityHours',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.SmallIntegerField()),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField()),
            ],
            options={
                'db_table': 'facility_hours',
                'managed': False,
            },
        ),
    ]
