# Generated by Django 6.1.1 on 2026-10-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EligibilityScreenings',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('screening_type', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=20)),
                ('preliminary_result', models.CharField(max_length=30)),
                ('rules_version', models.CharField(max_length=30)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'eligibility_screenings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScreeningAnswers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('answer_value', models.CharField(max_length=255)),
                ('is_flagged', models.BooleanField()),
                ('flag_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('answered_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'screening_answers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScreeningQuestions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question_code', models.CharField(max_length=50, unique=True)),
                ('question_text', models.TextField()),
                ('answer_type', models.CharField(max_length=20)),
                ('is_required', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('display_order', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'screening_questions',
                'managed': False,
            },
        ),
    ]
