# Generated by Django 6.1.1 on 2026-10-09 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BloodInventory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("blood_type", models.CharField(max_length=3)),
                ("component_type", models.CharField(max_length=30)),
                ("units_available", models.IntegerField()),
                ("low_threshold", models.IntegerField()),
                ("critical_threshold", models.IntegerField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "blood_inventory",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="InventoryTransactions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("transaction_type", models.CharField(max_length=30)),
                ("units_change", models.IntegerField()),
                ("reason", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "inventory_transactions",
                "managed": False,
            },
        ),
    ]
