# Generated by Django 6.1.1 on 2026-10-07 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=120, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('role', models.CharField(max_length=20)),
                ('account_status', models.CharField(max_length=20)),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('facility_type', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=80)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'facilities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DonorProfiles',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DB_CASCADE, primary_key=True, serialize=False, to='core.users')),
                ('phone', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('blood_type', models.CharField(max_length=3)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=80)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('next_eligible_date', models.DateField(blank=True, null=True)),
                ('emergency_available', models.BooleanField()),
            ],
            options={
                'db_table': 'donor_profiles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StaffProfiles',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DB_CASCADE, primary_key=True, serialize=False, to='core.users')),
                ('authorization_status', models.CharField(max_length=20)),
                ('authorization_declared_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'staff_profiles',
                'managed': False,
            },
        ),
    ]
